name: Check PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-gh-workflows:
    name: GitHub workflows
    uses: ./.github/workflows/check-gh-workflows.yml

  check-infra:
    name: Infra
    uses: ./.github/workflows/check-infra.yml
